In [ ]:
import cv2
import os
from os import listdir
from os.path import isfile, join

ucf_folder = '..\\UCF-101'
count = 1
for folder in listdir(ucf_folder):
    for avi_file in listdir(join(ucf_folder, folder)):
        video_cap = cv2.VideoCapture(join(ucf_folder, folder, avi_file))
        length = int(video_cap.get(cv2.CAP_PROP_FRAME_COUNT))

        pos = 0
        while pos + 5 < length:
            
            target_dir = ".\\data\\%d" % ((count/500)+1)
            try:
                os.stat(target_dir)
            except:
                os.mkdir(target_dir)

            video_cap.set(1, pos) # CV_CAP_PROP_POS_FRAMES = 1
            _, image = video_cap.read()
            image = cv2.resize(image, (256, 256))
            cv2.imwrite("%s\\frame_%d_1.png" % (target_dir, count), image)
            video_cap.set(1, pos+2) # CV_CAP_PROP_POS_FRAMES = 1
            _, image = video_cap.read()
            image = cv2.resize(image, (256, 256))
            cv2.imwrite("%s\\frame_%d_2.png" % (target_dir, count), image)
            video_cap.set(1, pos+4) # CV_CAP_PROP_POS_FRAMES = 1
            _, image = video_cap.read()
            image = cv2.resize(image, (256, 256))
            cv2.imwrite("%s\\frame_%d_3.png" % (target_dir, count), image)
            count += 1
            pos += 8
        
        print("%d trilets captured" % count)

#vidcap = cv2.VideoCapture('..\\UCF-101\\Archery\\v_Archery_g01_c01.avi')
#success,image = vidcap.read()
#count = 0
#success = True
#while success:
#cv2.imwrite("frame%d.jpg" % count, image)     # save frame as JPEG file      
#success,image = vidcap.read()
#print('Read a new frame: ', success)
#count += 1

In [5]:
import matplotlib.pyplot as plt
import numpy as np
import cv2

video_cap = cv2.VideoCapture("..\\UCF-101\\Archery\\v_Archery_g01_c01.avi")
length = int(video_cap.get(cv2.CAP_PROP_FRAME_COUNT))

pos = 0
while pos + 4 < length:
    video_cap.set(1, pos) # CV_CAP_PROP_POS_FRAMES = 1
    _, image = video_cap.read()
    image = cv2.resize(image, (256, 256))
    print(image.astype(np.float32))
    print(image.shape)
    #cv2.imwrite("%s\\frame_%d_1.png" % (target_dir, count), image)
    #plt.imshow(image)
    #plt.show()
    video_cap.set(1, pos+2) # CV_CAP_PROP_POS_FRAMES = 1
    _, image = video_cap.read()
    image = cv2.resize(image, (256, 256))
    #cv2.imwrite("%s\\frame_%d_2.png" % (target_dir, count), image)
    #plt.imshow(image)
    #plt.show()
    video_cap.set(1, pos+4) # CV_CAP_PROP_POS_FRAMES = 1
    _, image = video_cap.read()
    image = cv2.resize(image, (256, 256))
    #cv2.imwrite("%s\\frame_%d_3.png" % (target_dir, count), image)
    #plt.imshow(image)
    #plt.show()
    pos += 8

[[[ 135.  145.  157.]
  [ 118.  129.  140.]
  [  99.  109.  121.]
  ..., 
  [ 157.  174.  172.]
  [ 156.  173.  171.]
  [ 155.  172.  170.]]

 [[ 188.  198.  210.]
  [ 176.  186.  198.]
  [ 158.  167.  180.]
  ..., 
  [ 158.  175.  172.]
  [ 156.  173.  171.]
  [ 155.  172.  170.]]

 [[ 188.  200.  212.]
  [ 194.  205.  217.]
  [ 194.  206.  218.]
  ..., 
  [ 157.  175.  172.]
  [ 156.  173.  171.]
  [ 155.  172.  170.]]

 ..., 
 [[ 162.  150.  118.]
  [ 163.  151.  119.]
  [ 164.  153.  121.]
  ..., 
  [ 163.  143.  105.]
  [ 160.  140.  103.]
  [ 160.  140.  102.]]

 [[ 162.  150.  118.]
  [ 163.  151.  119.]
  [ 164.  153.  121.]
  ..., 
  [ 164.  144.  102.]
  [ 161.  141.   99.]
  [ 161.  141.   99.]]

 [[ 162.  150.  118.]
  [ 163.  151.  119.]
  [ 164.  153.  121.]
  ..., 
  [ 163.  142.  100.]
  [ 161.  141.   99.]
  [ 160.  140.   98.]]]
(256, 256, 3)
[[[ 156.  177.  173.]
  [ 159.  180.  176.]
  [ 157.  179.  174.]
  ..., 
  [ 156.  173.  172.]
  [ 155.  172.  170.]
  [ 155. 

[[[ 144.  168.  165.]
  [ 143.  167.  164.]
  [ 143.  167.  164.]
  ..., 
  [ 156.  177.  173.]
  [ 155.  175.  172.]
  [ 154.  174.  171.]]

 [[ 145.  169.  166.]
  [ 144.  168.  165.]
  [ 143.  167.  164.]
  ..., 
  [ 156.  177.  174.]
  [ 155.  175.  172.]
  [ 155.  175.  172.]]

 [[ 145.  169.  166.]
  [ 145.  169.  165.]
  [ 144.  168.  165.]
  ..., 
  [ 157.  177.  174.]
  [ 155.  175.  172.]
  [ 155.  175.  172.]]

 ..., 
 [[ 161.  148.  123.]
  [ 161.  148.  123.]
  [ 162.  149.  124.]
  ..., 
  [ 156.  137.  111.]
  [ 152.  134.  109.]
  [ 151.  133.  109.]]

 [[ 162.  149.  124.]
  [ 162.  149.  124.]
  [ 162.  150.  124.]
  ..., 
  [ 156.  137.  111.]
  [ 152.  134.  109.]
  [ 150.  132.  108.]]

 [[ 162.  149.  124.]
  [ 162.  149.  124.]
  [ 163.  149.  124.]
  ..., 
  [ 156.  137.  110.]
  [ 152.  134.  109.]
  [ 150.  132.  108.]]]
(256, 256, 3)
[[[ 146.  167.  166.]
  [ 146.  166.  165.]
  [ 145.  166.  165.]
  ..., 
  [ 159.  176.  174.]
  [ 157.  174.  172.]
  [ 157. 

In [ ]:
for i in range(1, 19499):
    print("%d\\frame_%d_1.png" % ((i/500)+1, i))
for i in range(1, 19499):
    print("%d\\frame_%d_2.png" % ((i/500)+1, i))
for i in range(1, 19499):
    print("%d\\frame_%d_3.png" % ((i/500)+1, i))

In [1]:
%run -i voxel_flow_train.py

train
Instructions for updating:
Use `tf.global_variables_initializer` instead.


FileNotFoundError: [Errno 2] No such file or directory: '/home/VoxelFlow/dataset/ucf101_triplets/10\\frame_4730_1.png'